export const languages = [
  { code: "en", label: "English", icon: "flag-outline" },
  { code: "ro", label: "Romanian", icon: "flag-outline" },
  { code: "fr", label: "French", icon: "flag-outline" },
  { code: "de", label: "German", icon: "flag-outline" },
  { code: "it", label: "Italian", icon: "flag-outline" },
  { code: "es", label: "Spanish", icon: "flag-outline" },
  { code: "pt", label: "Portuguese", icon: "flag-outline" },
  { code: "ru", label: "Russian", icon: "flag-outline" },
  { code: "zh", label: "Chinese", icon: "flag-outline" },
  { code: "ja", label: "Japanese", icon: "flag-outline" },
  { code: "ar", label: "Arabic", icon: "flag-outline" },
  { code: "hi", label: "Hindi", icon: "flag-outline" },
  { code: "bn", label: "Bengali", icon: "flag-outline" },
  { code: "ko", label: "Korean", icon: "flag-outline" },
  { code: "tr", label: "Turkish", icon: "flag-outline" },
  { code: "vi", label: "Vietnamese", icon: "flag-outline" },
  { code: "nl", label: "Dutch", icon: "flag-outline" },
  { code: "pl", label: "Polish", icon: "flag-outline" },
  { code: "sv", label: "Swedish", icon: "flag-outline" },
  { code: "th", label: "Thai", icon: "flag-outline" },
];

export const countryToLanguageMap: { [key: string]: string } = {
  US: "en",
  RO: "ro",
  FR: "fr",
  DE: "de",
  IT: "it",
  ES: "es",
  PT: "pt",
  RU: "ru",
  CN: "zh",
  JP: "ja",
  AE: "ar",
  IN: "hi",
  BD: "bn",
  KR: "ko",
  TR: "tr",
  VN: "vi",
  NL: "nl",
  PL: "pl",
  SE: "sv",
  TH: "th",
};
